---
- name: Add vimrc to defaults
  copy:
      src: vimrc
      dest: /etc/skel/.vimrc

- name: Ensure vim directories exist
  file: 
      path: /etc/skel/.vim/colors
      state: directory

- name: Add vim color scheme to defaults
  copy:
      src: azuki.vim
      dest: /etc/skel/.vim/colors/azuki.vim

- name: Add tmux.conf to defaults
  copy:
      src: tmux.conf
      dest: /etc/skel/.tmux.conf
