---
- name: create pentesters group
  group:
      name: pentesters
      state: present

- name: Update apt cache
  become: true
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Ensure standard packages are installed
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ standard_pentest_packages }}"

- name: install pip3 packages
  become: true
  pip:
      name: "{{ item }}"
      executable: pip3
      state: present
  with_items: "{{pentesting_pip3_modules}}"

- name: Check for nmap
  command: which nmap
  register: nmap_path
  failed_when: nmap_path.rc >= 2

- name: install nmap
  when: nmap_path.rc == 1
  git:
      repo: 'https://github.com/nmap/nmap'
      dest: /tmp/nmap

- name: configure nmap
  when: nmap_path.rc == 1
  become: true
  command: ./configure
  args:
      chdir: /tmp/nmap

- name: make nmap
  when: nmap_path.rc == 1
  become: true
  make:
      chdir: /tmp/nmap

- name: make install nmap
  when: nmap_path.rc == 1
  become: true
  make:
      chdir: /tmp/nmap
      target: install 

- name: Get Masscan
  git:
      repo: 'https://github.com/robertdavidgraham/masscan'
      dest: /tmp/masscan

- name: make masscan
  become: true
  make:
      chdir: /tmp/masscan

- name: make install masscan
  become: true
  make:
      chdir: /tmp/masscan
      target: install

- name: Get SecLists
  become: true
  git:
      repo: 'https://github.com/danielmiessler/SecLists'
      dest: /opt/seclists

- name: set SecLists Permissions
  become: true
  file:
      path: /opt/seclists
      owner: root
      group: pentesters
      mode: 0775
      recurse: yes
